apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: ingress-nginx
spec:
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - web.azerp.xyz
  secretName: tls-secret
  dnsNames:
  - web.azerp.xyz
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer