apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: service-account
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
  selector:
    app: service-account