kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-stardard-retain
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed