apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: service-accounts-neo4j
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: service-account-neo4j