apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev
  name: users-postgres-config
  labels:
    app: postgres
data:
  POSTGRES_HOST: users-database
  POSTGRES_DB: postgres
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: postgrespwd
  ENV_USERS: dev
  POSTGRES_PORT: "5434"
  IS_HTTPS: "false"