apiVersion: v1
kind: Service
metadata:
  name: users-database
  namespace: dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: dev-nodes
spec:
  loadBalancerIP: 20.44.210.149
  ports:
  - port: 5434
    protocol: TCP
    targetPort: 5432
  selector:
    app: users-postgres
  type: LoadBalancer
