apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-service-user-deployment
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: service-user
  template:
    metadata:
      labels:
        app: service-user
    spec:
      containers:
      - name: service-user
        resources:
          requests:
            cpu: 300m
            memory: 0.2Gi
          limits:
            cpu: 600m
            memory: 0.5Gi
        image: azure.azurecr.io/users:20210428.0.0.7-fce8ab25771c99f187f74eff29c7070230985a39-development
        envFrom:
          - configMapRef:
              name: users-postgres-config
        ports:
        - name: backend-port
          containerPort: 8000
      imagePullSecrets:
        - name: acr-auth