apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: service-contact
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8002
    protocol: TCP
  selector:
    app: service-contact